CREATE TABLE IF NOT EXISTS KipodEvent (
    id              BIGINT,
    topic           VARCHAR,
    module          VARCHAR,
    level           INT,
    source          VARCHAR,
    start_time      BIGINT,
    end_time        BIGINT,
    tags            ARRAY,
    channel         BIGINT,
    stream          BIGINT,
    alarm           BOOLEAN,
    processed       BOOLEAN,
    comment         VARCHAR,
    armed           BOOLEAN,
    commented_at    BIGINT,
    processed_at    BIGINT,
    kafka_offset    BIGINT,
    PRIMARY KEY (id) 
) WITH "template=partitioned,backups=0,affinitykey=id,atomicity=atomic";
